backend:
  name: git-gateway
  branch: formsubmissions # Branch to update (optional; defaults to master)
  squash_merges: true

site_url: https://indiaconferences.tech/
display_url: indiaconferences.tech
       
# publish_mode: editorial_workflow


# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Conference Data"
    name: "Conferences"
    folder: "_events"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}"
    files:
      - label: Conferences
        name: confs
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "Venue", name: "venue", widget: "string"}
          - {label: "Start Date", name: "start", widget: "date", format: "YYYY-MM-DD"}
          - {label: "End Date", name: "end", widget: "date", format: "YYYY-MM-DD"}
          - {label: "Event Website", name: "website", widget: "string"}
          - {label: "CFP? Link?", name: "cfp", widget: "string", default: "true, false, URL", required: false}
          - {label: "Scholarships? Link?", name: "scholarships", widget: "string", default: "true, false, URL", required: false}
          - {label: "Childcare? Link?", name: "childcare", widget: "string", default: "true, false, URL", required: false}
          - {label: "Description", name: "description", widget: "string"}