backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

publish_mode: editorial_workflow

site_url: https://indiaconferences.tech/
display_url: indiaconferences.tech
       
# publish_mode: editorial_workflow


# This line should *not* be indented
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections:
  - label: "Conference Data"
    name: "Conferences"
    files:
      - label: "Conference Data"
        name: "Confereces"
        file: "_data/conferences.yml"
        fields:
          - label: Conferences
            name: confs
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Venue", name: "venue", widget: "string"}
              - {display_date: "Display Date", name: "display_date", widget: "string", default: "01 January 2019"}
              - {label: "Start Date", name: "start", widget: "date", format: "YYYY-MM-DD"}
              - {label: "End Date", name: "end", widget: "date", format: "YYYY-MM-DD"}
              - {label: "Event Website", name: "website", widget: "string"}
              - {label: "CFP? Link?", name: "cfp", widget: "string", default: "true, false, URL", required: false}
              - {label: "Scholarships? Link?", name: "scholarships", widget: "string", default: "true, false, URL", required: false}
              - {label: "Childcare? Link?", name: "childcare", widget: "string", default: "true, false, URL", required: false}
              - {label: "Description", name: "description", widget: "string"}